name: workoutwarrior
description: "A new Flutter project."

publish_to: 'none'

version: 0.0.1+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  just_audio: ^0.9.32

  english_words: ^4.0.0
  provider: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/app_icon.png
    - assets/icons/profile.png
    - assets/icons/settings.png
    - assets/icons/social.png
    - assets/icons/leaderboard.png
    - assets/icons/bestiary.png
    - assets/icons/howto.png
    - assets/icons/go_forward.png
    - assets/icons/go_backward.png
    - assets/icons/back_button.png
    - assets/images/spotlight.png
    - assets/images/pushups.gif
    - assets/images/jumping_jacks.gif
    - assets/images/lunges.gif
    - assets/images/situps.gif
    - assets/images/squats.gif
    - assets/images/burpees.gif
    - assets/images/planking.gif
    - assets/images/jogging.gif
    - assets/images/avatar.png
    - assets/boss_artifacts/boss1_hidden.png
    - assets/boss_artifacts/boss1_revealed.png
    - assets/boss_artifacts/boss2_hidden.png
    - assets/boss_artifacts/boss2_revealed.png
    - assets/music/background_music.mp3